# -*- coding: utf-8 -*-
"""simle_gemini_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ptdmMJCY2gnTvgd7Epm9nXafqFNclkq
"""

!pip install google-generativeai

import google.generativeai as genai

# genai.configure(api_key=API_KEY)
# 🔑 Step 1: Paste your Gemini API key directly here
API_KEY = "AIzaSyAPJa2EwxeU6cCftN2r2TIHz9pBt5ZPjAA"  # <-- replace with your actual API key

# 🔧 Step 2: Configure Gemini
genai.configure(api_key=API_KEY)

# Load Gemini model
model = genai.GenerativeModel("gemini-2.5-flash") # Updated model name

print("🤖 Gemini Chatbot (type 'quit' to exit)\n")

# Keep chat history for context
history = []

while True:
    user_input = input("You: ")

    if user_input.lower() in ["quit", "exit"]:
        print("Bot: Goodbye! 👋")
        break

    # Add user input to chat history
    history.append({"role": "user", "parts": [user_input]})

    # Generate model response
    # The generate_content method now directly handles the history in the correct format
    response = model.generate_content(history)

    bot_reply = response.text.strip()
    print(f"Bot: {bot_reply}\n")

    # Add bot reply to history
    history.append({"role": "model", "parts": [bot_reply]})